/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './resources/js/**/*.{js,vue}',
    './resources/views/**/*.php',
  ],
  theme: {
    extend: {
      colors: {
        // Prussian Blue — dark navy for sidebar, headings, primary actions
        // Values come from CSS custom properties so themes can override them
        prussian: {
          50: 'rgb(var(--prussian-50) / <alpha-value>)',
          100: 'rgb(var(--prussian-100) / <alpha-value>)',
          200: 'rgb(var(--prussian-200) / <alpha-value>)',
          300: 'rgb(var(--prussian-300) / <alpha-value>)',
          400: 'rgb(var(--prussian-400) / <alpha-value>)',
          500: 'rgb(var(--prussian-500) / <alpha-value>)',
          600: 'rgb(var(--prussian-600) / <alpha-value>)',
          700: 'rgb(var(--prussian-700) / <alpha-value>)',
          800: 'rgb(var(--prussian-800) / <alpha-value>)',
          900: 'rgb(var(--prussian-900) / <alpha-value>)',
          950: 'rgb(var(--prussian-950) / <alpha-value>)',
        },
        // Wisteria — purple accent for interactive elements, buttons, highlights
        wisteria: {
          50: 'rgb(var(--wisteria-50) / <alpha-value>)',
          100: 'rgb(var(--wisteria-100) / <alpha-value>)',
          200: 'rgb(var(--wisteria-200) / <alpha-value>)',
          300: 'rgb(var(--wisteria-300) / <alpha-value>)',
          400: 'rgb(var(--wisteria-400) / <alpha-value>)',
          500: 'rgb(var(--wisteria-500) / <alpha-value>)',
          600: 'rgb(var(--wisteria-600) / <alpha-value>)',
          700: 'rgb(var(--wisteria-700) / <alpha-value>)',
          800: 'rgb(var(--wisteria-800) / <alpha-value>)',
          900: 'rgb(var(--wisteria-900) / <alpha-value>)',
          950: 'rgb(var(--wisteria-950) / <alpha-value>)',
        },
        // Lavender — light backgrounds, cards, subtle fills
        lavender: {
          50: 'rgb(var(--lavender-50) / <alpha-value>)',
          100: 'rgb(var(--lavender-100) / <alpha-value>)',
          200: 'rgb(var(--lavender-200) / <alpha-value>)',
          300: 'rgb(var(--lavender-300) / <alpha-value>)',
          400: 'rgb(var(--lavender-400) / <alpha-value>)',
          500: 'rgb(var(--lavender-500) / <alpha-value>)',
          600: 'rgb(var(--lavender-600) / <alpha-value>)',
          700: 'rgb(var(--lavender-700) / <alpha-value>)',
          800: 'rgb(var(--lavender-800) / <alpha-value>)',
          900: 'rgb(var(--lavender-900) / <alpha-value>)',
          950: 'rgb(var(--lavender-950) / <alpha-value>)',
        },
        // Golden Sand — warm accent for highlights, success, secondary actions
        sand: {
          50: 'rgb(var(--sand-50) / <alpha-value>)',
          100: 'rgb(var(--sand-100) / <alpha-value>)',
          200: 'rgb(var(--sand-200) / <alpha-value>)',
          300: 'rgb(var(--sand-300) / <alpha-value>)',
          400: 'rgb(var(--sand-400) / <alpha-value>)',
          500: 'rgb(var(--sand-500) / <alpha-value>)',
          600: 'rgb(var(--sand-600) / <alpha-value>)',
          700: 'rgb(var(--sand-700) / <alpha-value>)',
          800: 'rgb(var(--sand-800) / <alpha-value>)',
          900: 'rgb(var(--sand-900) / <alpha-value>)',
          950: 'rgb(var(--sand-950) / <alpha-value>)',
        },
        // Black — deepest text and contrast
        ink: {
          50: 'rgb(var(--ink-50) / <alpha-value>)',
          100: 'rgb(var(--ink-100) / <alpha-value>)',
          200: 'rgb(var(--ink-200) / <alpha-value>)',
          300: 'rgb(var(--ink-300) / <alpha-value>)',
          400: 'rgb(var(--ink-400) / <alpha-value>)',
          500: 'rgb(var(--ink-500) / <alpha-value>)',
          600: 'rgb(var(--ink-600) / <alpha-value>)',
          700: 'rgb(var(--ink-700) / <alpha-value>)',
          800: 'rgb(var(--ink-800) / <alpha-value>)',
          900: 'rgb(var(--ink-900) / <alpha-value>)',
          950: 'rgb(var(--ink-950) / <alpha-value>)',
        },
        // Kinhold brand palette (hardcoded, not themed)
        kin: {
          ivory: '#FAF8F5',
          cream: '#F5F2EE',
          white: '#FFFFFF',
          border: '#E8E4DF',
          'border-dark': '#2E2E32',
          black: '#1C1C1E',
          'off-white': '#F0EDE9',
          'bg-dark': '#121214',
          'surface-dark': '#1C1C20',
          'surface-dark-alt': '#252528',
          gold: '#C4975A',
          'gold-hover': '#D4A96A',
          'gold-active': '#B38A50',
          success: '#5B8C6A',
          warning: '#C48B3F',
          error: '#C45B5B',
          info: '#5B7B9C',
          'gray-50': '#F5F3F0',
          'gray-100': '#EDEBE7',
          'gray-200': '#D9D5CF',
          'gray-300': '#B8B3AB',
          'gray-400': '#8A857D',
          'gray-500': '#6B6966',
          'gray-600': '#4A4640',
          'gray-700': '#333028',
          'gray-800': '#252528',
          'gray-900': '#1C1C20',
        },
        // Distinct calendar event colors (not themed)
        cal: {
          blue: '#2f4a7a',
          purple: '#7d57a8',
          teal: '#0d9488',
          rose: '#be185d',
          amber: '#a5a84e',
          emerald: '#047857',
          sky: '#0369a1',
          fuchsia: '#a21caf',
          orange: '#c2410c',
          lime: '#4d7c0f',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(28, 28, 30, 0.06), 0 1px 2px -1px rgba(28, 28, 30, 0.04)',
        'card-lg': '0 4px 6px -1px rgba(28, 28, 30, 0.08), 0 2px 4px -2px rgba(28, 28, 30, 0.05)',
        'card-xl': '0 10px 15px -3px rgba(28, 28, 30, 0.1), 0 4px 6px -4px rgba(28, 28, 30, 0.05)',
        'glow': '0 0 20px rgba(196, 151, 90, 0.25)',
      },
      borderRadius: {
        card: '12px',
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 3s ease-in-out infinite',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.85' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2px)' },
        },
      },
      spacing: {
        'safe-bottom': 'max(1rem, env(safe-area-inset-bottom))',
      },
      minHeight: {
        'nav': '5rem',
      },
    },
  },
  plugins: [],
}
