applications:
  app:
    source:
      root: "/"
    type: "php:8.4"
    runtime:
      extensions:
        - redis
        - pdo_pgsql
    relationships:
      database: "db:postgresql"
      redis: "cache:redis"
    mounts:
      "/.config":
        source: "storage"
        source_path: "config"
      "bootstrap/cache":
        source: "storage"
        source_path: "cache"
      "storage":
        source: "storage"
        source_path: "storage"
    web:
      locations:
        "/":
          passthru: "/index.php"
          root: "public"
    workers:
      queue:
        commands:
          start: php artisan queue:work
      scheduler:
        commands:
          start: php artisan schedule:work
    variables:
      env:
        N_PREFIX: "/app/.global"
    dependencies:
      nodejs:
        n: "*"
    build:
      flavor: none
    hooks:
      build: |
        set -eux
        mkdir -p bootstrap/cache
        mkdir -p storage/framework/cache
        mkdir -p storage/framework/sessions
        mkdir -p storage/framework/views
        mkdir -p storage/logs
        composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader --no-dev
        n auto || n lts
        hash -r
        npm ci
        npm run build
      deploy: |
        set -eux
        mkdir -p storage/framework/sessions
        mkdir -p storage/framework/cache
        mkdir -p storage/framework/views
        php artisan migrate --force
        php artisan storage:link
        php artisan optimize:clear

services:
  db:
    type: postgresql:16
  cache:
    type: redis:7.2

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      headers: ["Accept", "Accept-Language", "Content-Language"]
      default_ttl: 300
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
